export const constantString = {
  EMPLOYEE_MANAGEMENT_APP: "Employee Management App",
  EMPLOYEE_INFORMATION: "Employee Information",
  FIRST_NAME: "First Name",
  ENTER_FIRST_NAME: "Enter First Name",
  ENTER_LAST_NAME: "Enter Last Name",
  LAST_NAME: "Last Name",
  GENDER: "Gender",
  MALE: "Male",
  FEMALE: "Female",
  ADD_EMPLOYEE: "Add Employee",
  UPDATE_EMPLOYEE: "Update Employee",
  UPDATE: "Update",
  DELETE: "Delete",
  NO: "No",
  SUBMIT: "Submit",
  SAVE: "Save",
  ACTIONS: "Actions",
  CLOSE: "Close",
  SELECT_GENDER: "Select Gender",
};
